dataservice/__init__.py,sha256=_NWjtHnQwCEXmjUeLeZ4cSrQaYA4T3s9snoKzF8WAGU,740
dataservice/_utils.py,sha256=Pmdo-n1vt9VJImjQopVSxkMnYavpfDqms9BCg5WceFU,600
dataservice/cache.py,sha256=4gKcypCmdN1-aPrCsnXekp7w4xCy83oN4i-I8LUfevA,3688
dataservice/clients.py,sha256=tZhESBULAdryIE1VeJFiErC6jAURytKyhaxda75lx5E,3694
dataservice/config.py,sha256=_2cjEILYmgKm6B4DZRGJgOWagdtxDkwznM0pNm9V7No,2337
dataservice/data.py,sha256=ULcxaAEWrFqvtur2Qtc4TJlQ-PSJrJ9c2_NeHhXhW-g,3125
dataservice/exceptions.py,sha256=2HqdX1gEM9SbLYaQX_Gyl3HnUkeQqeg0Y9ZNMA3xRUE,634
dataservice/files.py,sha256=ORiRtDtYBLaGnRQoXctOkMDm7q-C1HCnNxksihb6SBk,1999
dataservice/logs.py,sha256=2POOuBvIhHnp6R7e8eXRjt9mHPJthrj41cmRieXMmmU,1311
dataservice/models.py,sha256=b8G4dGSHKxLoGE3_lAmdHOASa_eE_k8--8sacnK2S1Y,4940
dataservice/pw_draft.py,sha256=n7YsPvh0ORNFUoWUtBJ01sl9RS5qYPAlWu01jody3Cs,543
dataservice/service.py,sha256=tm8wjv9X4Kl3PNTcFBwLP7Z5xS_lkkuMmjQVFYSoEt0,2832
dataservice/worker.py,sha256=dKyZjqx-g_Y7KQvImxCD4MbfN9bI9VWaKAG1olVpkfE,12499
python_dataservice-0.1.3.dist-info/LICENSE,sha256=YFuh1Fs-GEiQo-dmT_kAULdSQp9PNIda3yXzZIvCs8w,1068
python_dataservice-0.1.3.dist-info/METADATA,sha256=rRDdfEaP7WM_Kq4_5_DZUMemhusJNZn54Jqe6x6dMRk,3800
python_dataservice-0.1.3.dist-info/WHEEL,sha256=sP946D7jFCHeNz5Iq4fL4Lu-PrWrFsgfLXbbkciIZwg,88
python_dataservice-0.1.3.dist-info/RECORD,,
