# tests/test_exception_handler.py

